// app/lyceum/components/data/modules.ts
export interface Chapter {
  id: number;
  title: string;
  description: string;
  videoId?: string;   // YouTube video ID
  duration?: string;
  content?: string;
}

export interface Module {
  id: number;
  title: string;
  description: string;
  chapters: number;
  imageUrl: string;
  chapterList: Chapter[];
}

export const modules: Module[] = [
  {
    id: 1,
    title: "Introduction to Stock Markets",
    description:
      "Learn the basics of stock markets, how they work, and the key concepts every trader should know.",
    chapters: 15,
    imageUrl:
      "https://images.unsplash.com/photo-1651341050677-24dba59ce0fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdG9jayUyMG1hcmtldCUyMHRyYWRpbmd8ZW58MXx8fHwxNzYzMTA1OTExfDA&ixlib=rb-4.1.0&q=80&w=1080",
    chapterList: [
      {
        id: 1,
        title: "The Need to Invest",
        description:
          "Learn about the importance of savings. Identify avenues to invest the savings in suitable investment vehicle. Compare historical returns generated by different assets, and know what to expect from your investments.",
        videoId: "INTRO_STOCKS_1", // replace with real YouTube ID
        duration: "00:08:25",
        content:
          "Investing is one of the most important financial decisions you'll make in your life. Understanding why you need to invest, rather than just save, is crucial for building long-term wealth and achieving your financial goals.\n\nThe primary reason to invest is to beat inflation. When you simply save money in a bank account, inflation erodes its purchasing power over time. Investing allows your money to grow at a rate that potentially exceeds inflation, preserving and increasing your wealth.\n\nThere are several investment vehicles available:\n\n1. Equities (Stocks): Ownership in companies that can provide returns through capital appreciation and dividends.\n\n2. Fixed Income (Bonds): Debt instruments that provide regular interest payments.\n\n3. Real Estate: Physical property that can appreciate in value and generate rental income.\n\n4. Gold: A traditional store of value and hedge against inflation.\n\nHistorically, equities have provided the highest returns over long periods, averaging 12-15% annually in Indian markets. However, they also come with higher volatility and risk. Understanding your risk tolerance and investment horizon is crucial for choosing the right investment mix."
      },
      {
        id: 2,
        title: "Regulators, the guardians of capital markets",
        description:
          "Find out who and how the regulators govern the financial markets and also understand different types of financial market participants. Understand the need to regulate the markets.",
        videoId: "INTRO_STOCKS_2", // replace with real YouTube ID
        duration: "00:08:58",
        content:
          "Financial markets require strong regulatory oversight to ensure fairness, transparency, and investor protection. In India, several regulatory bodies work together to maintain market integrity.\n\nSEBI (Securities and Exchange Board of India):\nThe primary regulator for securities markets in India. SEBI's main objectives are:\n- Protecting investor interests\n- Promoting and regulating securities markets\n- Preventing fraudulent and unfair trade practices\n\nRBI (Reserve Bank of India):\nRegulates monetary policy, banking sector, and foreign exchange markets.\n\nKey Market Participants:\n1. Investors (Retail and Institutional)\n2. Stock Exchanges (BSE, NSE)\n3. Brokers and Sub-brokers\n4. Depositories (NSDL, CDSL)\n5. Mutual Funds\n6. FIIs and DIIs\n\nRegulations are essential to prevent market manipulation, insider trading, and ensure fair price discovery. SEBI has implemented various measures like circuit breakers, margin requirements, and disclosure norms to protect market integrity."
      },
      {
        id: 3,
        title: "Market Intermediaries",
        description:
          "An overview of the financial intermediaries in the Indian stock market and the services they offer.",
        videoId: "INTRO_STOCKS_3", // replace with real YouTube ID
        duration: "00:08:07",
        content:
          "Market intermediaries play a crucial role in facilitating smooth trading and settlement operations in stock markets. Understanding their roles helps investors navigate the market effectively.\n\nStockbrokers:\n- Facilitate buying and selling of securities\n- Provide trading platforms and research\n- Must be registered with SEBI and stock exchanges\n\nDepository Participants (DPs):\n- Provide demat account services\n- Hold securities in electronic form\n- Facilitate transfer and settlement\n\nRegistrar and Transfer Agents:\n- Maintain records of shareholders\n- Process corporate actions like dividends, bonus shares\n- Handle IPO applications\n\nMerchant Bankers:\n- Assist companies in raising capital\n- Manage IPO and FPO processes\n- Provide advisory services\n\nCustodians:\n- Hold securities on behalf of FIIs and mutual funds\n- Ensure safe custody and settlement\n\nUnderstanding these intermediaries helps investors choose the right partners for their investment journey and ensures they receive proper services and protection."
      },
      {
        id: 4,
        title: "The IPO Markets (Part 1)",
        description:
          "Understand the origins of business and the funding environment of business. Learn about the different funding stages and also learn how funding works.",
        videoId: "INTRO_STOCKS_4", // replace with real YouTube ID
        duration: "00:03:51",
        content:
          "Initial Public Offerings (IPOs) represent a significant milestone in a company's journey from a private entity to a publicly traded corporation. Understanding the IPO process is essential for investors looking to participate in these opportunities.\n\nBusiness Funding Stages:\n\n1. Bootstrap/Self-Funding:\nFounders invest their own money to start the business.\n\n2. Angel Investors:\nHigh net-worth individuals provide early-stage funding in exchange for equity.\n\n3. Venture Capital:\nProfessional investors provide larger funding rounds for growing companies.\n\n4. Private Equity:\nLarge investments in mature private companies.\n\n5. IPO (Going Public):\nCompany offers shares to the public for the first time.\n\nWhy Companies Go Public:\n- Raise capital for expansion\n- Provide exit options for early investors\n- Enhance company visibility and credibility\n- Create currency for acquisitions (stock)\n- Attract and retain talent through stock options\n\nThe IPO process involves significant preparation, including financial audits, regulatory compliance, and roadshows to attract investors."
      },
      {
        id: 5,
        title: "The IPO Markets (Part 2)",
        description:
          "Learn the basics of the IPO market and the process of how to go about investing in IPOs. This chapter also helps us understand the different IPO jargons that are commonly used.",
        videoId: "INTRO_STOCKS_5", // replace with real YouTube ID
        duration: "00:07:07",
        content:
          "Participating in IPOs requires understanding various terms, processes, and how to apply for shares.\n\nKey IPO Terms:\n\n1. Price Band:\nThe range within which investors can bid for shares.\n\n2. Lot Size:\nMinimum number of shares that can be applied for.\n\n3. Subscription:\nNumber of times the IPO has been applied for versus shares available.\n\n4. Allotment:\nProcess of allocating shares to applicants.\n\n5. Listing Day:\nFirst day the stock trades on the exchange.\n\nIPO Categories:\n- Retail Individual Investors (RII): Up to ₹2 lakhs\n- High Net-worth Individuals (HNI): Above ₹2 lakhs\n- Qualified Institutional Buyers (QIB): Banks, mutual funds, etc.\n\nHow to Apply:\n1. Have a demat account and trading account\n2. Check IPO details in newspapers or financial websites\n3. Apply through ASBA (blocked amount in bank)\n4. Wait for allotment results\n5. Shares credited to demat account before listing\n\nResearch the company thoroughly before investing, including financials, business model, and valuations."
      }
    ]
  },
  {
    id: 2,
    title: "Technical Analysis",
    description:
      "Master the art of reading charts, understanding patterns, and using technical indicators to make informed trading decisions.",
    chapters: 18,
    imageUrl:
      "https://images.unsplash.com/photo-1748609622257-bb917eda4d14?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWNobmljYWwlMjBhbmFseXNpc3xlbnwxfHx8fDE3NjMxNTQyOTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    chapterList: [
      {
        id: 1,
        title: "Introduction to Technical Analysis",
        description:
          "Understanding the basics of technical analysis, its principles, and how it differs from fundamental analysis.",
        videoId: "TECH_ANALYSIS_1", // replace with real YouTube ID
        duration: "00:10:15",
        content:
          "Technical analysis is the study of historical price movements and patterns to predict future price behavior. It's based on three core principles:\n\n1. Price discounts everything\n2. Price moves in trends\n3. History tends to repeat itself\n\nTechnical analysts use charts and indicators to identify trading opportunities."
      },
      {
        id: 2,
        title: "Candlestick Patterns",
        description:
          "Learn about Japanese candlestick patterns and how to interpret them for trading decisions.",
        videoId: "TECH_ANALYSIS_2", // replace with real YouTube ID
        duration: "00:12:30",
        content:
          "Candlestick charts provide visual representation of price action. Key patterns include:\n\n- Doji: Indecision in the market\n- Hammer: Potential bullish reversal\n- Shooting Star: Potential bearish reversal\n- Engulfing patterns: Strong reversal signals\n\nUnderstanding these patterns helps traders identify entry and exit points."
      }
    ]
  },
  {
    id: 3,
    title: "Fundamental Analysis",
    description:
      "Understand how to evaluate a company's financial health, read balance sheets, and determine intrinsic value.",
    chapters: 22,
    imageUrl:
      "https://images.unsplash.com/photo-1744473119469-905016183836?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaW5hbmNpYWwlMjBhbmFseXNpcyUyMGNoYXJ0c3xlbnwxfHx8fDE3NjMwNjc4MDl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    chapterList: [
      {
        id: 1,
        title: "Overview of Financial Statements",
        description:
          "Understanding the three main financial statements: Balance Sheet, Income Statement, and Cash Flow Statement.",
        videoId: "FUNDAMENTAL_1", // replace with real YouTube ID
        duration: "00:15:20",
        content:
          "Financial statements are essential documents that show a company's financial health. The three main statements are interconnected and provide different perspectives on the company's performance and position."
      }
    ]
  },
  {
    id: 4,
    title: "Futures Trading",
    description:
      "Deep dive into futures contracts, margin requirements, hedging strategies, and how to trade in the derivatives market.",
    chapters: 16,
    imageUrl:
      "https://images.unsplash.com/photo-1730382625230-3756013c515c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMGdyb3d0aCUyMHN0cmF0ZWd5fGVufDF8fHx8MTc2MzE1NDI5MHww&ixlib=rb-4.1.0&q=80&w=1080",
    chapterList: [
      {
        id: 1,
        title: "Introduction to Futures",
        description:
          "Understanding futures contracts, how they work, and their role in the derivatives market.",
        videoId: "FUTURES_1", // replace with real YouTube ID
        duration: "00:11:45",
        content:
          "Futures are standardized contracts to buy or sell an asset at a predetermined price on a future date. They are used for hedging and speculation in financial markets."
      }
    ]
  },
  {
    id: 5,
    title: "Options Trading Strategies",
    description:
      "Learn about options contracts, Greeks, various strategies like straddles, spreads, and how to manage risk effectively.",
    chapters: 20,
    imageUrl:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbnZlc3RtZW50JTIwcG9ydGZvbGlvfGVufDF8fHx8MTc2MzEyNDg2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    chapterList: [
      {
        id: 1,
        title: "Options Basics",
        description:
          "Understanding call and put options, option premium, strike price, and expiry dates.",
        videoId: "OPTIONS_1", // replace with real YouTube ID
        duration: "00:13:30",
        content:
          "Options give the right, but not the obligation, to buy or sell an asset at a specific price. Learn the fundamentals of how options work and their key characteristics."
      }
    ]
  },
  {
    id: 6,
    title: "Risk Management & Trading Psychology",
    description:
      "Master the mental aspects of trading, position sizing, stop losses, and strategies to protect your capital.",
    chapters: 14,
    imageUrl:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaW5hbmNpYWwlMjBwbGFubmluZ3xlbnwxfHx8fDE3NjMxMzg3OTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    chapterList: [
      {
        id: 1,
        title: "Psychology of Trading",
        description:
          "Understanding emotional biases, fear, greed, and how to develop a disciplined trading mindset.",
        videoId: "RISK_PSYCH_1", // replace with real YouTube ID
        duration: "00:09:50",
        content:
          "Trading psychology is often more important than technical knowledge. Learn to manage emotions, stick to your trading plan, and avoid common psychological pitfalls."
      }
    ]
  }
];
